name: CI workflow
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/ci.yaml'
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/ci.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configura JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Configura dependencias do Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Instala dependencias do Maven
        run: mvn install

      - name: Executa testes
        run: mvn -Dspring.profiles.active=test --batch-mode --update-snapshots verify

      - name: 🚀 Coveralls Coverage Report Submission
        run: mvn coveralls:report --define repoToken=${{ secrets.COVERALL_REPO_TOKEN }}

      - name: Analisa com SonarCloud
        run: mvn -B verify sonar:sonar -Dspring.profiles.active=test -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}